# Generated by Django 3.2.3 on 2021-06-01 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ngo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=200)),
                ('ngo_website', models.URLField(default=None)),
                ('ngo_aim', models.CharField(max_length=250)),
                ('ngolocation', models.TextField()),
                ('ngostate', models.CharField(default=None, max_length=80)),
                ('ngopincode', models.CharField(default=None, max_length=50)),
                ('associated', models.TextField()),
                ('ngo_head', models.CharField(max_length=50)),
                ('phone_num', models.CharField(max_length=50)),
                ('ngo_email', models.EmailField(max_length=254)),
                ('ngo_whatsapp', models.CharField(max_length=50)),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='IndiDonar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('donarname', models.CharField(default=None, max_length=70)),
                ('donaraddress', models.CharField(default=None, max_length=100)),
                ('donarphone', models.CharField(default=None, max_length=13)),
                ('isbn', models.CharField(default=0, max_length=50)),
                ('donarwhatsapp', models.CharField(default=None, max_length=50)),
                ('donarcity', models.CharField(default=None, max_length=100)),
                ('donaremail', models.EmailField(default=None, max_length=254)),
                ('donar_pincode', models.CharField(default=None, max_length=20)),
                ('donarstate', models.CharField(default=None, max_length=50)),
                ('bookname', models.CharField(default=None, max_length=150)),
                ('authorname', models.CharField(default=None, max_length=100)),
                ('publisher_detail', models.TextField(default=None)),
                ('genre', models.CharField(default=None, max_length=50)),
                ('bookphoto', models.ImageField(default=None, upload_to='images/')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('acc_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookDonater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donarname', models.CharField(default=None, max_length=70)),
                ('donarphone', models.CharField(default=None, max_length=13)),
                ('isbn', models.CharField(default=0, max_length=50)),
                ('donarwhatsapp', models.CharField(default=None, max_length=50)),
                ('donaraddress', models.CharField(default=None, max_length=100)),
                ('donarcity', models.CharField(default=None, max_length=100)),
                ('donaremail', models.EmailField(default=None, max_length=254)),
                ('donar_pincode', models.CharField(default=None, max_length=20)),
                ('donarstate', models.CharField(default=None, max_length=50)),
                ('bookname', models.CharField(default=None, max_length=150)),
                ('authorname', models.CharField(default=None, max_length=100)),
                ('publisher_detail', models.TextField(default=None)),
                ('genre', models.CharField(default=None, max_length=50)),
                ('bookphoto', models.ImageField(default=None, upload_to='images/')),
                ('auth_token', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('acc_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
