# Generated by Django 3.2.3 on 2021-06-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_indidonar_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indidonar',
            name='board',
            field=models.CharField(blank=True, default='cbse', max_length=50),
        ),
    ]
