# Generated by Django 3.2.3 on 2021-06-25 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profiles_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='auth_token',
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='is_verified',
        ),
    ]
