# Generated by Django 3.2.3 on 2021-05-25 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=150)),
                ('bookpublisher', models.CharField(max_length=150)),
                ('bookauthor', models.CharField(max_length=150)),
                ('isbn', models.CharField(max_length=100)),
                ('offeredprice', models.IntegerField(default=0)),
                ('offered', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=200)),
                ('reseller_name', models.CharField(default='seller', max_length=50)),
                ('reseller_contact', models.CharField(max_length=50)),
                ('reseller_whatsapp', models.CharField(max_length=50)),
                ('reseller_address', models.TextField()),
                ('reseller_city', models.CharField(max_length=100)),
                ('reseller_pincode', models.IntegerField()),
                ('reseller_state', models.CharField(max_length=100)),
                ('book_photo', models.ImageField(upload_to='images/')),
                ('auth_token', models.CharField(default=0, max_length=50)),
                ('acc_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
