# Generated by Django 3.2.3 on 2021-05-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='auth_token',
        ),
    ]
