# Generated by Django 3.2.3 on 2021-05-27 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0002_remove_seller_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
