# Generated by Django 3.2.3 on 2021-06-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resell', '0004_seller_actualprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='board',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
